INTRO
Imagine all the minds in this world were connected, everyone could see each other thought, imagination, memories…you could truly understand everyone actions, their situations, their pain, joy, emotions and everything else.
Imagine everyone in the world focused on accomplishing one task, Imagine all what could be accomplished, I could start listing but I want you to imagine yourself… Great right! 
Well this thought has been on my mind for a while now so I decided to write it down… Enjoy!
The origin of Varia!
In the universe there are infinite galaxies, and in these galaxies there are different planets… one major problem all planets face is extinction at a certain point, the star at the middle of the solar system slowly pulls all planets around it to their fiery death. Variter, the most civilized and technologically advanced planet the universe, on the quest of solving this problem, some scientist in variter created an alternate dimension called varia or k dimension[k-d].
VARIA the K-dimension
  THE SYNC: this is a process necessary to access the pathway to varia, it is a process that involves voluntarily sharing all thoughts,experience,memories,and imaginations with the varion, the varion then links you to varia, the link to varia automatically activates the dormant part of the brain, giving the synced access to k-d and full control over the brain. 
 Everyone that has been synced has limited access to varia, only the Varion which is leader of varia named after the lead scientist in Variter, has full access to the k-d. The synced could read each others thought, and communicate with telepathy, while the varion had the ability to physically appear in k-d which was like another world, the varion could shift between both worlds willingly, he also has abilities like telekinesis when he is in k-d. To gain access to the k-d all the scientist involved had to go through the sync, but not all were successful some of them did not survive the process as their minds were completely taken from them because varia was unstable then. Four out of the twelve died physically but there minds were uploaded to varia. “When a synced dies the mind fully crosses over to k-d”
During this period all other planets in Variters galaxy was already dead or dying, and Variter was on the brink of death too, not enough time to come up with a cure for their planet, they synced as many people as they could, and then used a dying planets core to create a power source for a spacecraft called  VZTON 2000, the lead scientist and two others took varia and left their galaxy to find a new home for varia, and chose another Varion. The three of them entered CRYO SLEEP which they programmed to automatically wake them up when they arrive in a new galaxy. Upon the death of their galaxy as expected all the synced crossed over to k-d.
The journey of varia!
After traveling millions of light years varia finally,arrived at a new galaxy called the Bsiaton, there were four habitable planets in this galaxy, turns out they were facing the same problem as Variter, and they were also very advanced in science although not as advanced as Variter, they were happy to accept help from Variter, varia quickly found a new varion one in each planet and successfully synced majority of all four planets together, they archived a lot this time, it turns out that the more minds varia got the more stable and powerful it becomes, it started with the varions, they started manifesting extraordinary abilities due to using their brains to full capacity they had more strength, could move faster, could communicate with nature and use natural energy and also use telekinesis outside k-d, after some years some gifted members also started to developed unique abilities but it could only work while in varia, attempting to use special abilities in the real world could prove fatal for the synced, only the varions could use their abilities in both worlds, they were also trying to create a portal that would make fully appearing in varia possible without death and could also make people leave varia and appear in the real world physically, but this idea was a bit far-fetched at the time. So much was accomplished during this time including adding hyperspace tech to their spacecraft to allow intergalactic traveling faster and more convenient but varia main objective was still incomplete they couldn’t find a way to stop the death of planets, sooner or later they had to move to another galaxy in other to complete their objective.
Varia continue moving across different galaxies gathering data, minds, and getting stronger, billions of years past, after all the research and data collection they came up with an hypothesis of the characteristics needed from a planet to make it eternal…
-it must be a young planet in a new galaxy
-it must have a balanced temperature
-it must be the only habitable planet in the galaxy
-it must have a natural moon
-it must have water
-and so on…
Unfortunately, it was almost impossible to find such planet around at that time, and it will take trillions of years before a galaxy like that would naturally occur and over 97% possibility that even if one occurs they would not be able to find it in time. So they decided to improvise and  make one!!!
The creation of the perfect galaxy
Twelve stars were targeted, massive stars that were selected in tribute to the twelve scientists that built varia, each stars were deprived of their nuclear fuel, and allowed to turn to a supernova. The process was watched and controlled given each experiment all it needed to form a galaxy, the experiment has now entered the cooling phase which would normally take billions of years but the experiment was controlled so it took less time, but still the cooling period was still too long for them to wait out so they decided to continue their search, hoping to return to meet successful galaxies.
Billions of year’s later varia had colonized over 20 more planets and gotten much stronger,they returned to the site of the experiment out of 12 only 2 survived. The milky way and the phoenix.
They decided to stabilize, the phoenix first which was way bigger than Milky-Way, the phoenix had 3 habitable planets during the process of stabilizing the galaxy the sun got deprived of fuel and with imminent threat to explode, varia allowed it to consume all the planet to prevent a supernova which could affect the milky way because both galaxies were close. They later destroyed the galaxy by creating a black hole close to it. Going back to their last option milky-way which had no planets and one dwarf star as the sun. Close by there was a new galaxy forming probably from one of the failed experiments, they used this to their advantage and allowed both galaxies merge given the Milky-Way the contents it was lacking, without too much work the merge was successful and the galaxy became quickly stable, with 12 planets named after the 12 scientist that started varia, 3 planets were unstable and ended up falling out of there orbit leaving only 9 planets, finally they have accomplished what they wanted milky way was stable and immortal, the sun gravitational pull was countered by the planets speed revolving around the sun and there moon revolving around each planet, and every billion year the sun core is changed to prevent the sun from growing to a red giant,there were 2 planets that had tendencies of supporting life, earth and mars, both planets were explored and genes were scattered around to speed up the creation of life.
At this point varia had run out of energy,they have used up so much in trying to stabilize the phoenix, creating black holes, merging milky way, stabilizing the earth sun and on transportation, and they didn’t have enough to make a jump to another galaxy to gather more energy, they also couldn’t live in the new planet because they had no portal yet, so they had to ditch there ship, and hibernate on earth until mankind has evolved for varia to select another varion and begin the sync, they used the remaining energy to crystallize varia and stored all the energy they had left in the single crystal fragment varia had become, They had finally built a home and are satisfied with it so they hid varia in a very secured location on earth until someone or something eventually comes in contact with it after that it will take the form of whatever awakens it and then search for a new varion.
millions of years passed and as they imagined life bloomed on earth, civilization along with science and technologies was progressing because of mankind curiosity, but at a very slow pace. In the quest of understanding their origin, many follows deep beliefs like religions and cultures while some stood with science and continued doing researches and coming up with hypothesis and theories about mankind origin…
Varia awakens!!!